### ISSUE TITLE
Document how to go from the DOCX example of a list to a working list question in an interview

### ISSUE THREAD

**Issue by samglover** [SuffolkLITLab/AssemblyLine-docs#473]
In the [DOCX documentation](https://assemblyline.suffolklitlab.org/docs/docx#start-by-just-adding-the-basic-variables-in-your-docx-template-without-repeated-elements-or-advanced-code:~:text=Here%20is%20an%20example%20of%20a%20DOCX%20template%3A), it recommends this format for a list of items:

```
* {%p for item in problems %}
* {{ item }}
* {%p endfor %}
```

From this, the Weaver creates two generic questions:

```yaml
---
id: Item
question: |
  Item
fields:
  - "Item": item
---
id: Problems
question: |
  Problems
fields:
  - "Problems": problems
---
```

We should document how to go from the Weaver-generated questions to an actual list.
